# Scikit_learn_New_Data

In [2]:
# standerd imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
df = pd.read_csv('cleaned_phone_data.csv')
df

,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690.0,1529.000000,1819.000000,36,5.00,8.0,2000.0,10-2020
1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803.0,1659.000000,2489.000000,36,5.00,16.0,2000.0,9-2020
2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803.0,1659.000000,2489.000000,36,5.00,16.0,2000.0,9-2020
3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803.0,1659.000000,2489.000000,36,5.00,16.0,2000.0,9-2020
4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999.0,7716.018672,9883.410788,10,5.71,16.0,3000.0,4-2020
...,...,...,...,...,...,...,...,...,...,...,...,...
1021,Apple,iPhone XS Max 512GB Space Gray (MT622),iOS,842,27190.0,21150.000000,30200.000000,47,6.50,512.0,3174.0,9-2018
1022,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685.0,16018.000000,27900.000000,61,6.50,64.0,3174.0,9-2018
1023,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600.0,21939.000000,33720.000000,28,6.50,64.0,3174.0,9-2018
1024,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804.0,7999.000000,9999.000000,18,6.26,128.0,3750.0,11-2019
1025,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755.0,18500.000000,19010.000000,2,6.65,128.0,4500.0,10-2020