# Scikit_learn_New_Data

In [1]:
# standerd imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
df = pd.read_csv('mobile_detail.csv')
df

,ratings,price,imgURL,corpus,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,https://rukminim2.flixcart.com/image/312/312/x...,storage128 gbram6 systemandroid 12processor t...,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,https://rukminim2.flixcart.com/image/312/312/k...,storage128 gbram6 gbexpandable storage256gb s...,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
2,4.2,13149,https://rukminim2.flixcart.com/image/312/312/x...,storage64 gbram4 systemandroid 11processor sp...,redmi,Note 11,white,64,android,NaN,Full HD,6.4
3,4.1,21999,https://rukminim2.flixcart.com/image/312/312/x...,storage256 gbram12 systemandroid q 11processo...,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,https://rukminim2.flixcart.com/image/312/312/k...,storage128 systemios 15processor typea15 bion...,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1979,4.2,29999,https://rukminim2.flixcart.com/image/312/312/k...,storage256 gbram12 systemandroid pie 9 pie ox...,oneplus,7 Pro,blue,256,android,NaN,2K,6.7
1980,4.1,15999,https://rukminim2.flixcart.com/image/312/312/x...,storage128 gbram6 gbexpandable storage1tb sys...,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,https://rukminim2.flixcart.com/image/312/312/k...,storage64 gbram4 gbexpandable storage512gb sy...,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1982,3.9,30203,https://rukminim2.flixcart.com/image/312/312/x...,storage128 gbram8 systemandroid 11processor s...,oneplus,9 5G,black,128,android,NaN,Full HD,6.5
1983,4.4,13999,https://rukminim2.flixcart.com/image/312/312/x...,storage128 gbram6 systemandroid 13processor t...,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [21]:
df = df.drop(columns='corpus')
df = df.drop(columns='imgURL')
df

,ratings,price,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
2,4.2,13149,redmi,Note 11,white,64,android,NaN,Full HD,6.4
3,4.1,21999,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
...,...,...,...,...,...,...,...,...,...,...
1979,4.2,29999,oneplus,7 Pro,blue,256,android,NaN,2K,6.7
1980,4.1,15999,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1982,3.9,30203,oneplus,9 5G,black,128,android,NaN,Full HD,6.5
1983,4.4,13999,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [3]:
df.isnull().sum()
df = df.dropna()

In [4]:
df.isnull().sum()

ratings           0
price             0
brand             0
mobile_name       0
color             0
storage           0
system            0
processor_type    0
resolution        0
size              0
dtype: int64

In [5]:
# df.info()
df.columns

Index(['ratings', 'price', 'brand', 'mobile_name', 'color', 'storage',
       'system', 'processor_type', 'resolution', 'size'],
      dtype='object')

In [6]:
df['resolution'].unique()

array(['Full HD', '4K', 'HD', '2K'], dtype=object)

In [7]:
df['price']
df

,ratings,price,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,iPhone 6s Plus,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,Y3s,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,iPhone 8,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [8]:
# Build ML Models
X = df.drop('price', axis = 1)
X = df.drop('mobile_name', axis = 1)
y = df['price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.20)

In [9]:
X

,ratings,price,brand,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,gold,128,android,mediatek,Full HD,6.6

In [10]:
# Build ML model
from sklearn.ensemble import RandomForestRegressor
phon_model = RandomForestRegressor()
phon_model.fit(X_train, y_train)
phon_model.score(X_test, y_test)

ValueError: could not convert string to float: 'redmi'

In [11]:
X

,ratings,price,brand,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,gold,128,android,mediatek,Full HD,6.6

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Assuming X is your DataFrame
feature_cat = ['brand', 'color', 'system', 'processor_type', 'resolution']

# Define the OneHotEncoder and ColumnTransformer
encoder = OneHotEncoder(sparse_output=False)  # `drop='first'` to avoid dummy variable trap
trans = ColumnTransformer(
    transformers=[("featured_final", encoder, feature_cat)],
    remainder="passthrough")

# Apply the transformation
transformed_X = trans.fit_transform(X)
pd.DataFrame(transformed_X)
# Get feature names for the resulting DataFrame
# feature_names = (encoder.get_feature_names_out(feature_cat)
                  # .tolist() + list(X.columns.difference(feature_cat)))

# Create a DataFrame with the transformed data
# transformed_df = pd.DataFrame(transformed_X, columns=feature_names)

# Display the DataFrame
# print(transformed_df)

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.2,23999.0,128.0,6.7
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.5,20999.0,128.0,6.5
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,21999.0,256.0,6.4
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.6,3537.0,128.0,5.4
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,4.5,5537.0,64.0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.3,9490.0,32.0,6.5
1639,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.5,11464.0,256.0,4.7
1640,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,15999.0,128.0,6.5
1641,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.3,11999.0,64.0,6.5
1642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.4,13999.0,128.0,6.6

In [13]:
# encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
feature_cat = ["brand","color", "system","processor_type","resolution"]
featured = OneHotEncoder(sparse_output=False, drop='first')
trans = ColumnTransformer([("featured_final",featured,feature_cat)],
                         remainder = "passthrough")
transformed_X = trans.fit_transform(X)

pd.DataFrame(transformed_X)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.2,23999.0,128.0,6.7
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.5,20999.0,128.0,6.5
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,4.1,21999.0,256.0,6.4
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.6,3537.0,128.0,5.4
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,4.5,5537.0,64.0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.3,9490.0,32.0,6.5
1639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.5,11464.0,256.0,4.7
1640,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,15999.0,128.0,6.5
1641,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.3,11999.0,64.0,6.5
1642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.4,13999.0,128.0,6.6

In [14]:
# 2nd method for encoding
tranafoed_m = pd.get_dummies(df[['brand', 'color', 'system', 'processor_type', 'resolution']])
tranafoed_m

,brand_apple,brand_infinix,brand_mi,brand_motorola,brand_oneplus,brand_oppo,brand_realme,brand_redmi,brand_samsung,brand_tecno,...,system_ios,processor_type_apple,processor_type_mediatek,processor_type_qualcomm,processor_type_samsung,processor_type_unisoc,resolution_2K,resolution_4K,resolution_Full HD,resolution_HD
0,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,True,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,True,False
5,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1977,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
1978,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,True
1980,False,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
1981,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,True,False
1983,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [15]:
# lets refit model
# from sklearn.model_selection import train_test_split
Z = tranafoed_m
X_train, X_test, y_train, y_test = train_test_split(transformed_X,y, test_size=.30)
# Build ML model
from sklearn.ensemble import RandomForestRegressor
phon_model = RandomForestRegressor()
phon_model.fit(X_train, y_train)
phon_model.score(X_test, y_test)

0.9941497269470132

In [16]:
for i in range(10,200,10):
    print(f'Running Model with {i} Estimatores')
    clf = RandomForestRegressor(n_estimators=i).fit(X_train, y_train)
    print(f'Accuracy is: {clf.score(X_test, y_test)}')

Running Model with 10 Estimatores
Accuracy is: 0.9964431758121858
Running Model with 20 Estimatores
Accuracy is: 0.9928800175815476
Running Model with 30 Estimatores
Accuracy is: 0.9948873519523806
Running Model with 40 Estimatores
Accuracy is: 0.9943494078990086
Running Model with 50 Estimatores
Accuracy is: 0.9964291794821952
Running Model with 60 Estimatores
Accuracy is: 0.9962002961474687
Running Model with 70 Estimatores
Accuracy is: 0.9946741965968712
Running Model with 80 Estimatores
Accuracy is: 0.9959170857941522
Running Model with 90 Estimatores
Accuracy is: 0.9933758638770132
Running Model with 100 Estimatores
Accuracy is: 0.9947737296309851
Running Model with 110 Estimatores
Accuracy is: 0.9951327355053319
Running Model with 120 Estimatores
Accuracy is: 0.9951048162077869
Running Model with 130 Estimatores
Accuracy is: 0.9957143253279515
Running Model with 140 Estimatores
Accuracy is: 0.9958688839936376
Running Model with 150 Estimatores
Accuracy is: 0.9944142420737224
Running Model with 160 Estimatores
Accuracy is: 0.996357842864052
Running Model with 170 Estimatores
Accuracy is: 0.9943291869921927
Running Model with 180 Estimatores
Accuracy is: 0.9950122878542985
Running Model with 190 Estimatores
Accuracy is: 0.9953142488970106

In [17]:
# Save model
import pickle as pc
pc.dump(clf,open('Phone_model_predictor.pkl','wb'))

In [18]:
load_model = pc.load(open('Phone_model_predictor.pkl','rb'))
load_model.score(X_test, y_test)

0.9953142488970106

In [23]:
df.isnull().sum()

ratings             0
price               0
brand               0
mobile_name         0
color               0
storage             0
system              0
processor_type    340
resolution          0
size                1
dtype: int64

In [26]:
df.dropna(subset=["processor_type"], inplace=True)
df.dropna(subset=["size"], inplace=True)
df.isna().sum()

ratings           0
price             0
brand             0
mobile_name       0
color             0
storage           0
system            0
processor_type    0
resolution        0
size              0
dtype: int64

In [27]:
df

,ratings,price,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,iPhone 6s Plus,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,Y3s,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,iPhone 8,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [30]:
# split X and y
X = df.drop('price', axis = 1)
y = df['price']

In [32]:
# imputaition
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
# fill categorical variables
cat_features  = SimpleImputer(strategy='constant', fill_value='missing')
sim_card_fatures  = SimpleImputer(strategy='constant', fill_value='4')
num_feature = SimpleImputer(strategy = 'mean')
# assigning values
cat_feature = ['make','color']
simcar_feature = ['sim_cards']
num_feature = ['memory(kb)']
imputer = ColumnTransformer([('cat_features', cat_features, 'cat_feature'),
                             ('simcar_feature', sim_card_features, 'simcar_feature'),
                            ('num_feature', num_feature, 'num_feature')])
filled_X = imputer.fit_trandformer(X)

NameError: name 'sim_card_features' is not defined