# Scikit_learn_New_Data

In [1]:
# standerd imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('mobile_detail.csv')
df = df.drop(columns='corpus')
df = df.drop(columns='imgURL')
df

,ratings,price,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
2,4.2,13149,redmi,Note 11,white,64,android,NaN,Full HD,6.4
3,4.1,21999,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
...,...,...,...,...,...,...,...,...,...,...
1979,4.2,29999,oneplus,7 Pro,blue,256,android,NaN,2K,6.7
1980,4.1,15999,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1982,3.9,30203,oneplus,9 5G,black,128,android,NaN,Full HD,6.5
1983,4.4,13999,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [3]:
df.isnull().sum()
df = df.dropna()

In [4]:
df.isnull().sum()

ratings           0
price             0
brand             0
mobile_name       0
color             0
storage           0
system            0
processor_type    0
resolution        0
size              0
dtype: int64

In [5]:
# df.info()
df.columns

Index(['ratings', 'price', 'brand', 'mobile_name', 'color', 'storage',
       'system', 'processor_type', 'resolution', 'size'],
      dtype='object')

In [6]:
df['resolution'].unique()

array(['Full HD', '4K', 'HD', '2K'], dtype=object)

In [7]:
df['price']
df

,ratings,price,brand,mobile_name,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,Note 12 Pro 5G,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,F11 Pro,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,Nord CE 5G,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,iPhone 13 mini,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,iPhone 6s Plus,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,Y3s,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,iPhone 8,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,g72,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,Note 9,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,T2x 5G,gold,128,android,mediatek,Full HD,6.6

In [8]:
# Build ML Models
X = df.drop('price', axis = 1)
X = df.drop('mobile_name', axis = 1)
y = df['price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.20)

In [9]:
X

,ratings,price,brand,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,gold,128,android,mediatek,Full HD,6.6

In [10]:
# Build ML model
from sklearn.ensemble import RandomForestRegressor
phon_model = RandomForestRegressor()
phon_model.fit(X_train, y_train)
phon_model.score(X_test, y_test)

ValueError: could not convert string to float: 'oppo'

In [11]:
X

,ratings,price,brand,color,storage,system,processor_type,resolution,size
0,4.2,23999,redmi,black,128,android,mediatek,Full HD,6.7
1,4.5,20999,oppo,green,128,android,mediatek,Full HD,6.5
3,4.1,21999,oneplus,blue,256,android,qualcomm,Full HD,6.4
4,4.6,3537,apple,blue,128,ios,apple,Full HD,5.4
5,4.5,5537,apple,gold,64,ios,apple,4K,5.5
...,...,...,...,...,...,...,...,...,...
1977,4.3,9490,vivo,blue,32,android,mediatek,HD,6.5
1978,4.5,11464,apple,grey,256,ios,apple,HD,4.7
1980,4.1,15999,motorola,grey,128,android,mediatek,Full HD,6.5
1981,4.3,11999,redmi,black,64,android,mediatek,Full HD,6.5
1983,4.4,13999,vivo,gold,128,android,mediatek,Full HD,6.6

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Assuming X is your DataFrame
feature_cat = ['brand', 'color', 'system', 'processor_type', 'resolution']

# Define the OneHotEncoder and ColumnTransformer
encoder = OneHotEncoder(sparse_output=False)  # `drop='first'` to avoid dummy variable trap
trans = ColumnTransformer(
    transformers=[("featured_final", encoder, feature_cat)],
    remainder="passthrough")

# Apply the transformation
transformed_X = trans.fit_transform(X)
pd.DataFrame(transformed_X)
# Get feature names for the resulting DataFrame
# feature_names = (encoder.get_feature_names_out(feature_cat)
                  # .tolist() + list(X.columns.difference(feature_cat)))

# Create a DataFrame with the transformed data
# transformed_df = pd.DataFrame(transformed_X, columns=feature_names)

# Display the DataFrame
# print(transformed_df)

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.2,23999.0,128.0,6.7
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.5,20999.0,128.0,6.5
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,21999.0,256.0,6.4
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.6,3537.0,128.0,5.4
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,4.5,5537.0,64.0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.3,9490.0,32.0,6.5
1639,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.5,11464.0,256.0,4.7
1640,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,15999.0,128.0,6.5
1641,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.3,11999.0,64.0,6.5
1642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.4,13999.0,128.0,6.6

In [16]:
# encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
feature_cat = ["brand","color", "system","processor_type","resolution"]
featured = OneHotEncoder(sparse_output=False, drop='first')
trans = ColumnTransformer([("featured_final",featured,feature_cat)],
                         remainder = "passthrough")
transformed_X = trans.fit_transform(X)

pd.DataFrame(transformed_X)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.2,23999.0,128.0,6.7
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.5,20999.0,128.0,6.5
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,4.1,21999.0,256.0,6.4
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.6,3537.0,128.0,5.4
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,4.5,5537.0,64.0,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.3,9490.0,32.0,6.5
1639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.5,11464.0,256.0,4.7
1640,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.1,15999.0,128.0,6.5
1641,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.3,11999.0,64.0,6.5
1642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.4,13999.0,128.0,6.6

In [17]:
# 2nd method for encoding
tranafoed_m = pd.get_dummies(df[['brand', 'color', 'system', 'processor_type', 'resolution']])
tranafoed_m

,brand_apple,brand_infinix,brand_mi,brand_motorola,brand_oneplus,brand_oppo,brand_realme,brand_redmi,brand_samsung,brand_tecno,...,system_ios,processor_type_apple,processor_type_mediatek,processor_type_qualcomm,processor_type_samsung,processor_type_unisoc,resolution_2K,resolution_4K,resolution_Full HD,resolution_HD
0,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,True,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,True,False
5,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1977,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
1978,True,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,True
1980,False,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
1981,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,True,False
1983,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [46]:
# lets refit model
# from sklearn.model_selection import train_test_split
Z = tranafoed_m
X_train, X_test, y_train, y_test = train_test_split(transformed_X,y, test_size=.30)
# Build ML model
from sklearn.ensemble import RandomForestRegressor
phon_model = RandomForestRegressor()
phon_model.fit(X_train, y_train)
phon_model.score(X_test, y_test)

0.996437227345053

In [47]:
for i in range(10,200,10):
    print(f'Running Model with {i} Estimatores')
    clf = RandomForestRegressor(n_estimators=i).fit(X_train, y_train)
    print(f'Accuracy is: {clf.score(X_test, y_test)}')

Running Model with 10 Estimatores
Accuracy is: 0.9915884745692494
Running Model with 20 Estimatores
Accuracy is: 0.9980650363577431
Running Model with 30 Estimatores
Accuracy is: 0.9962062634991358
Running Model with 40 Estimatores
Accuracy is: 0.9976016918074925
Running Model with 50 Estimatores
Accuracy is: 0.9959360204653579
Running Model with 60 Estimatores
Accuracy is: 0.9971868118162986
Running Model with 70 Estimatores
Accuracy is: 0.9956655249276233
Running Model with 80 Estimatores
Accuracy is: 0.9971251701861347
Running Model with 90 Estimatores
Accuracy is: 0.9974688495167272
Running Model with 100 Estimatores
Accuracy is: 0.9970977077189819
Running Model with 110 Estimatores
Accuracy is: 0.9968269297495475
Running Model with 120 Estimatores
Accuracy is: 0.9964175878229424
Running Model with 130 Estimatores
Accuracy is: 0.9965875835523479
Running Model with 140 Estimatores
Accuracy is: 0.9974157253874002
Running Model with 150 Estimatores
Accuracy is: 0.9973197286474418
Running Model with 160 Estimatores
Accuracy is: 0.9976789168767514
Running Model with 170 Estimatores
Accuracy is: 0.9964925432441473
Running Model with 180 Estimatores
Accuracy is: 0.9964975887230523
Running Model with 190 Estimatores
Accuracy is: 0.9971866642891933

In [48]:
# Save model
import pickle as pc
pc.dump(clf,open('Phone_model_predictor.pkl','wb'))

In [49]:
load_model = pc.load(open('Phone_model_predictor.pkl','rb'))
load_model.score(X_test, y_test)

0.9971866642891933